// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Header.css'
;

function Header(Props) {
  var title = Props.title;
  return React.createElement("header", {
              className: "pokedex-header-wrapper"
            }, React.createElement("h1", undefined, title));
}

var make = Header;

export {
  make ,
  
}
/*  Not a pure module */
