// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Title(Props) {
  var label = Props.label;
  return React.createElement("h1", undefined, label);
}

var make = Title;

export {
  make ,
  
}
/* react Not a pure module */
